Comment in scripts.js added
rafprzygoda/jslearn pull request #2
Opened 2017-05-26 19:08 UTC by rafprzygoda

Dodałem komentarz linowy i blokowy w scripts.js

2017-05-27 08:06 UTC, matwjablonski requested changes

2017-05-27 08:06 UTC, matwjablonski commented on js/scripts.js
> +//Jest to zadanie 8.4 - dodawanie komentarzy a to jest komentarz linowy
write it in english

2017-05-27 08:06 UTC, matwjablonski commented on js/scripts.js
>  // scripts.js czyli pierwszy skrypt w JS
write it in english

2017-05-27 08:06 UTC, matwjablonski commented on js/scripts.js
> +/* To natomiast jest komentarz blokowy
yes, but in english :)

2017-05-28 19:48 UTC, rafprzygoda commented
Cześć, podmieniłem komentarze na j. angielski

2017-05-29 07:30 UTC, matwjablonski approved these changes

2017-05-29 16:43 UTC, merged